/* =====================================================================
   FACE-OFF: NETWORK+  —  ACRONYM POOL
   Exam: CompTIA Network+ N10-009
   ---------------------------------------------------------------------
   GENERATED FILE — do not hand-edit.
   Rebuild with:  python3 tools/build-acronyms.py
   Source of truth: the NETWORK+ acronym repo's data/acronyms.json.

   135 acronyms in 16 categories.

   THERE IS NO DIFFICULTY RAMP IN AN ACRONYM. Nothing makes MAC a 100
   and SD-WAN a 500, which is a problem on a board whose whole shape is
   a column climbing 100 to 500. So the ramp is the TASK, not the item:
   the cheap rows ask you to expand the letters, the middle rows give
   you a description and ask which acronym it is, and the dear rows
   give you the acronym and ask what it actually does. Same acronym,
   three difficulties — which is also why 135 acronyms go a long way.

   The clue text is built at draw time from these three fields, so
   there is no answer bank to memorise and editing an acronym here
   changes every form of it at once.

     ac = the acronym          ex = what the letters stand for
     df = what it actually does
     amb = set only when this acronym means something else somewhere
           in the bank; the clue names this field so the team is not
           marked wrong for giving the other correct expansion.

   Categories with fewer than 5 entries cannot fill a five-row column
   and are skipped on the largest boards. They still play on shorter
   boards and in the Lightning Final. Currently: Storage, Reliability Metrics.
   ===================================================================== */

window.FACEOFF_ACRONYMS = {
  categories: [
    { name: "IP ADDRESSING & DNS",
      items: [
      { ac: "DHCP",
        ex: "Dynamic Host Configuration Protocol",
        df: "Automatically assigns IP addresses." },
      { ac: "DNS",
        ex: "Domain Name System",
        df: "Translates domain names into IP addresses." },
      { ac: "DNSSEC",
        ex: "Domain Name System Security Extensions",
        df: "Secures DNS from spoofing attacks." },
      { ac: "DoH",
        ex: "DNS over HTTPS",
        df: "Encrypts DNS queries using HTTPS." },
      { ac: "DoT",
        ex: "DNS over TLS",
        df: "Encrypts DNS queries using TLS." },
      { ac: "CIDR",
        ex: "Classless Inter-domain Routing",
        df: "Flexible IP addressing method." },
      { ac: "VLSM",
        ex: "Variable Length Subnet Mask",
        df: "Allows different subnet sizes." },
      { ac: "NAT",
        ex: "Network Address Translation",
        df: "Converts private IPs to public IPs." },
      { ac: "PAT",
        ex: "Port Address Translation",
        df: "Allows many devices to share one public IP." },
      { ac: "IPAM",
        ex: "Internet Protocol Address Management",
        df: "Tracks and manages IP addresses." },
      { ac: "FQDN",
        ex: "Fully Qualified Domain Name",
        df: "Complete domain name (e.g., www.google.com)." },
      { ac: "CNAME",
        ex: "Canonical Name",
        df: "Alias for another domain name." },
      { ac: "MX",
        ex: "Mail Exchange",
        df: "Identifies email servers." },
      { ac: "PTR",
        ex: "Pointer Record",
        df: "Maps IP to domain name." },
      { ac: "NS",
        ex: "Name Server",
        df: "Identifies DNS servers for a domain." },
      { ac: "SOA",
        ex: "Start of Authority",
        df: "Contains DNS zone authority information." },
      ] },
    { name: "HARDWARE & CABLING",
      items: [
      { ac: "NIC",
        ex: "Network Interface Card",
        df: "Connects device to network." },
      { ac: "AP",
        ex: "Access Point",
        df: "Provides wireless access." },
      { ac: "WAP",
        ex: "Wireless Access Point",
        df: "Same as AP." },
      { ac: "MDF",
        ex: "Main Distribution Frame",
        df: "Primary network hub location." },
      { ac: "IDF",
        ex: "Intermediate Distribution Frame",
        df: "Secondary network hub." },
      { ac: "DAC",
        ex: "Direct Attach Copper",
        df: "Short-distance high-speed cable." },
      { ac: "BNC",
        ex: "Bayonet Neill–Concelman",
        df: "Coaxial cable connector." },
      { ac: "LC",
        ex: "Local Connector",
        df: "Fiber connector type." },
      { ac: "SC",
        ex: "Subscriber Connector",
        df: "Fiber connector type." },
      { ac: "ST",
        ex: "Straight Tip",
        df: "Fiber connector type." },
      { ac: "MPO",
        ex: "Multifiber Push On",
        df: "Multi-fiber connector." },
      { ac: "UTP",
        ex: "Unshielded Twisted Pair",
        df: "Standard Ethernet cable." },
      { ac: "STP",
        ex: "Shielded Twisted Pair",
        amb: "Hardware & Cabling",
        df: "Cable with shielding." },
      { ac: "PoE",
        ex: "Power over Ethernet",
        df: "Sends power over network cable." },
      { ac: "QSFP",
        ex: "Quad Small Form-factor Pluggable",
        df: "High-speed transceiver." },
      { ac: "SFP",
        ex: "Small Form-factor Pluggable",
        df: "Network interface module." },
      ] },
    { name: "SECURITY PROTOCOLS",
      items: [
      { ac: "AES",
        ex: "Advanced Encryption Standard",
        df: "Strong encryption standard used globally." },
      { ac: "IPSec",
        ex: "Internet Protocol Security",
        df: "Encrypts network traffic." },
      { ac: "AH",
        ex: "Authentication Header",
        df: "Provides authentication for IP packets." },
      { ac: "ESP",
        ex: "Encapsulating Security Payload",
        df: "Encrypts and authenticates IP traffic." },
      { ac: "SSL",
        ex: "Secure Sockets Layer",
        df: "Older encryption protocol." },
      { ac: "TLS",
        ex: "Transport Layer Security",
        df: "Modern secure encryption protocol." },
      { ac: "PKI",
        ex: "Public Key Infrastructure",
        df: "Manages encryption keys and certificates." },
      { ac: "PSK",
        ex: "Pre-shared Key",
        df: "Shared password for encryption." },
      { ac: "TKIP",
        ex: "Temporal Key Integrity Protocol",
        df: "Older wireless encryption method." },
      { ac: "WPA",
        ex: "Wi-Fi Protected Access",
        df: "Secure wireless encryption standard." },
      { ac: "WEP",
        ex: "Wired Equivalent Privacy",
        df: "Weak, outdated wireless encryption." },
      { ac: "WPS",
        ex: "Wi-Fi Protected Setup",
        df: "Simplifies Wi-Fi setup (less secure)." },
      ] },
    { name: "ROUTING & SWITCHING",
      items: [
      { ac: "BGP",
        ex: "Border Gateway Protocol",
        df: "Routes traffic between large networks on the Internet." },
      { ac: "OSPF",
        ex: "Open Shortest Path First",
        df: "Finds the shortest path for data in a network." },
      { ac: "RIP",
        ex: "Routing Information Protocol",
        df: "Uses hop count to determine best route." },
      { ac: "EIGRP",
        ex: "Enhanced Interior Gateway Routing Protocol",
        df: "Cisco routing protocol for efficient routing decisions." },
      { ac: "IS-IS",
        ex: "Intermediate System to Intermediate System",
        df: "Routing protocol used in large service provider networks." },
      { ac: "STP",
        ex: "Spanning Tree Protocol",
        amb: "Routing & Switching",
        df: "Prevents loops in switched networks." },
      { ac: "RSTP",
        ex: "Rapid Spanning Tree Protocol",
        df: "Faster version of STP." },
      { ac: "LACP",
        ex: "Link Aggregation Control Protocol",
        df: "Combines multiple links into one connection." },
      { ac: "FHRP",
        ex: "First Hop Redundancy Protocol",
        df: "Provides backup gateways." },
      { ac: "HSRP",
        ex: "Hot Standby Router Protocol",
        df: "Cisco redundancy protocol for routers." },
      { ac: "VRRP",
        ex: "Virtual Router Redundancy Protocol",
        df: "Standard protocol for gateway redundancy." },
      ] },
    { name: "NETWORKING FUNDAMENTALS",
      items: [
      { ac: "IP",
        ex: "Internet Protocol",
        df: "Assigns addresses to devices and ensures data is sent to the correct destination across a network." },
      { ac: "TCP",
        ex: "Transmission Control Protocol",
        df: "Reliable protocol that ensures data is delivered completely and in order." },
      { ac: "UDP",
        ex: "User Datagram Protocol",
        df: "Fast protocol that sends data without guaranteeing delivery." },
      { ac: "MAC",
        ex: "Media Access Control",
        df: "Unique hardware address assigned to a network interface." },
      { ac: "MTU",
        ex: "Maximum Transmission Unit",
        df: "Largest packet size that can be sent over a network." },
      { ac: "TTL",
        ex: "Time to Live",
        df: "Limits how long a packet can travel before being discarded." },
      { ac: "ARP",
        ex: "Address Resolution Protocol",
        df: "Maps IP addresses to MAC addresses on a local network." },
      { ac: "ICMP",
        ex: "Internet Control Message Protocol",
        df: "Used for diagnostics and error reporting (like ping)." },
      { ac: "IGMP",
        ex: "Internet Group Management Protocol",
        df: "Manages multicast group memberships." },
      { ac: "OSI",
        ex: "Open Systems Interconnection",
        df: "7-layer model describing how data moves across a network." },
      ] },
    { name: "NETWORK TYPES & INFRASTRUCTURE",
      items: [
      { ac: "LAN",
        ex: "Local Area Network",
        df: "Network in a small area like a home or office." },
      { ac: "WAN",
        ex: "Wide Area Network",
        df: "Connects multiple LANs across large distances." },
      { ac: "WLAN",
        ex: "Wireless Local Area Network",
        df: "LAN that uses Wi-Fi instead of cables." },
      { ac: "VLAN",
        ex: "Virtual Local Area Network",
        df: "Logically separates networks on the same hardware." },
      { ac: "VPC",
        ex: "Virtual Private Cloud",
        df: "Private network hosted within a cloud provider." },
      { ac: "VRF",
        ex: "Virtual Routing and Forwarding",
        df: "Allows multiple routing tables on one device." },
      { ac: "VXLAN",
        ex: "Virtual Extensible LAN",
        df: "Extends VLANs across large networks." },
      { ac: "SDN",
        ex: "Software-defined Network",
        df: "Network controlled by software instead of hardware." },
      { ac: "SD-WAN",
        ex: "Software-defined Wide Area Network",
        df: "Uses software to optimize WAN traffic routing." },
      { ac: "MPLS",
        ex: "Multiprotocol Label Switching",
        df: "Speeds up traffic using labels instead of IP lookups." },
      ] },
    { name: "SECURITY CONCEPTS",
      items: [
      { ac: "CIA",
        ex: "Confidentiality, Integrity, Availability",
        df: "Core goals of cybersecurity." },
      { ac: "MFA",
        ex: "Multifactor Authentication",
        df: "Uses multiple forms of verification." },
      { ac: "NAC",
        ex: "Network Access Control",
        df: "Controls who can access the network." },
      { ac: "IAM",
        ex: "Identity and Access Management",
        df: "Manages users and permissions." },
      { ac: "DLP",
        ex: "Data Loss Prevention",
        df: "Prevents sensitive data leaks." },
      { ac: "ZTA",
        ex: "Zero Trust Architecture",
        df: "Trust no device by default." },
      { ac: "UTM",
        ex: "Unified Threat Management",
        df: "Combines multiple security tools." },
      { ac: "SASE",
        ex: "Secure Access Service Edge",
        df: "Cloud-based networking and security." },
      { ac: "SSE",
        ex: "Security Service Edge",
        df: "Cloud-delivered security services." },
      { ac: "WAF",
        ex: "Web Application Firewall",
        df: "Protects web apps from attacks." },
      ] },
    { name: "SYSTEMS & INTERFACES",
      items: [
      { ac: "OS",
        ex: "Operating System",
        df: "Software that manages hardware and apps." },
      { ac: "GUI",
        ex: "Graphical User Interface",
        df: "Visual interface (windows/icons)." },
      { ac: "CLI",
        ex: "Command Line Interface",
        df: "Text-based interface." },
      { ac: "API",
        ex: "Application Programming Interface",
        df: "Allows software to communicate." },
      { ac: "IIS",
        ex: "Internet Information Services",
        df: "Microsoft web server." },
      { ac: "VNC",
        ex: "Virtual Network Computing",
        df: "Remote desktop access tool." },
      { ac: "RDP",
        ex: "Remote Desktop Protocol",
        df: "Microsoft remote access protocol." },
      ] },
    { name: "CLOUD & VIRTUALIZATION",
      items: [
      { ac: "IaaS",
        ex: "Infrastructure as a Service",
        df: "Cloud provides hardware resources." },
      { ac: "PaaS",
        ex: "Platform as a Service",
        df: "Cloud provides platform for apps." },
      { ac: "SaaS",
        ex: "Software as a Service",
        df: "Cloud provides software access." },
      { ac: "NaaS",
        ex: "Network as a Service",
        df: "Cloud-based networking services." },
      { ac: "VM",
        ex: "Virtual Machine",
        df: "Virtual computer running inside a host." },
      { ac: "NFV",
        ex: "Network Functions Virtualization",
        df: "Virtualized network services." },
      { ac: "IaC",
        ex: "Infrastructure as Code",
        df: "Managing infrastructure via code." },
      ] },
    { name: "POLICIES & COMPLIANCE",
      items: [
      { ac: "AUP",
        ex: "Acceptable Use Policy",
        df: "Rules for system usage." },
      { ac: "EULA",
        ex: "End User License Agreement",
        df: "Software usage contract." },
      { ac: "NDA",
        ex: "Non-Disclosure Agreement",
        df: "Protects confidential data." },
      { ac: "MOU",
        ex: "Memorandum of Understanding",
        df: "Agreement between parties." },
      { ac: "SLA",
        ex: "Service-Level Agreement",
        df: "Defines service expectations." },
      { ac: "GDPR",
        ex: "General Data Protection Regulation",
        df: "EU privacy law." },
      { ac: "PCI DSS",
        ex: "Payment Card Industry Data Security Standard",
        df: "Secures payment data." },
      ] },
    { name: "WIRELESS NETWORKING",
      items: [
      { ac: "SSID",
        ex: "Service Set Identifier",
        df: "Name of a Wi-Fi network." },
      { ac: "BSSID",
        ex: "Basic Service Set Identifier",
        df: "MAC address of access point." },
      { ac: "ESSID",
        ex: "Extended Service Set Identifier",
        df: "Name for extended wireless network." },
      { ac: "RSSI",
        ex: "Received Signal Strength Indicator",
        df: "Measures Wi-Fi signal strength." },
      { ac: "MIMO",
        ex: "Multiple Input Multiple Output",
        df: "Uses multiple antennas for performance." },
      { ac: "LTE",
        ex: "Long-Term Evolution",
        df: "4G wireless communication standard." },
      ] },
    { name: "SECURITY MONITORING",
      items: [
      { ac: "DoS",
        ex: "Denial of Service",
        df: "Overloads a system to make it unavailable." },
      { ac: "DDoS",
        ex: "Distributed Denial of Service",
        df: "Attack from multiple systems." },
      { ac: "IDS",
        ex: "Intrusion Detection System",
        df: "Detects suspicious activity." },
      { ac: "IPS",
        ex: "Intrusion Prevention System",
        df: "Detects and blocks threats." },
      { ac: "SIEM",
        ex: "Security Information and Event Management",
        df: "Collects and analyzes security logs." },
      ] },
    { name: "HARDWARE COMPONENTS",
      items: [
      { ac: "CPU",
        ex: "Central Processing Unit",
        df: "The brain of the computer." },
      { ac: "PSU",
        ex: "Power Supply Unit",
        df: "Supplies power to components." },
      { ac: "UPS",
        ex: "Uninterruptible Power Supply",
        df: "Backup power device." },
      { ac: "APU",
        ex: "Audio Processing Unit",
        df: "Handles audio tasks." },
      { ac: "PDU",
        ex: "Power Distribution Unit",
        df: "Distributes power in racks." },
      ] },
    { name: "INDUSTRIAL & IOT",
      items: [
      { ac: "IoT",
        ex: "Internet of Things",
        df: "Smart connected devices." },
      { ac: "IIoT",
        ex: "Industrial Internet of Things",
        df: "IoT used in industry." },
      { ac: "ICS",
        ex: "Industrial Control Systems",
        df: "Controls industrial processes." },
      { ac: "SCADA",
        ex: "Supervisory Control and Data Acquisition",
        df: "Monitors industrial systems." },
      { ac: "OT",
        ex: "Operational Technology",
        df: "Systems used in industrial environments." },
      ] },
    { name: "STORAGE",
      items: [
      { ac: "DAS",
        ex: "Direct Attached Storage",
        df: "Storage directly connected to device." },
      { ac: "NAS",
        ex: "Network Attached Storage",
        df: "Storage accessible over network." },
      { ac: "SAN",
        ex: "Storage Area Network",
        df: "High-speed storage network." },
      { ac: "FC",
        ex: "Fibre Channel",
        df: "High-speed storage protocol." },
      ] },
    { name: "RELIABILITY METRICS",
      items: [
      { ac: "MTBF",
        ex: "Mean Time Between Failures",
        df: "Average time before failure." },
      { ac: "MTTR",
        ex: "Mean Time To Repair",
        df: "Average repair time." },
      { ac: "RTO",
        ex: "Recovery Time Objective",
        df: "Max acceptable downtime." },
      { ac: "RPO",
        ex: "Recovery Point Objective",
        df: "Max acceptable data loss." },
      ] },
  ]
};
